name: fuzz-beta

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup gotip
      run: |
        go get golang.org/dl/gotip
        gotip download dev.fuzz
        go mod init
        
    - name: Fuzz
      run: gotip test -fuzz=FuzzImage
      # continue-on-error: true # uncomment to run until job timeout, if result as step error, skip and upload the result

    - name: Upload Current State
      if: always() # even on previous timeout or cancel
      uses: actions/upload-artifact@v2
      with:
        name: Fuzz-Results
        path: |
          testdata/corpus
        if-no-files-found: warn
        retention-days: 7
